
"use client"
import type { Metadata } from "next";
import { Geist, Geist_Mono, } from "next/font/google";
import { Michroma } from "next/font/google";
import "./globals.css";
import { Toaster } from "../components/toaster";
import { useAuthStore } from "@/store/authStore";
 import { useEffect } from "react";
import { useRouter } from "next/navigation";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const michroma = Michroma({
  weight: "400",
  variable: "--font-michroma",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { accessToken } = useAuthStore();
  const router = useRouter();

  useEffect(() => {
    console.log(accessToken)
    if (!accessToken) {
      router.push('/login');
    }
  }, [accessToken, router])
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${michroma.variable} antialiased`}
      >
        {children}
        <Toaster />
      </body>
    </html>
  );
}
