name: Admin Frontend CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout repo
      - name: Checkout code
        uses: actions/checkout@v3

      # Setup SSH with private key
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.DEPLOY_KEY }}

      # Deploy to server
      - name: Deploy to Contabo admin frontend
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
            cd /var/www/admin.beatpasal.com || mkdir -p /var/www/admin.beatpasal.com && cd /var/www/admin.beatpasal.com

            # Initialize git if not exists
            if [ ! -d ".git" ]; then
              git init
              git remote add origin git@github.com:Neomatrix-Nepal/beat-frontend.git
              git fetch
              git checkout -t origin/main
            else
              git pull origin main
            fi

            # Install dependencies
            npm install --production

            # Build project
            npm run build

            # Start/restart with PM2
            pm2 restart admin-beatpasal || pm2 start npm --name admin-beatpasal -- start
          EOF
